Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: sms_webhook_smsmessage

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/sms_webhook/views.py", line 155, in get
    total_sms = SMSMessage.objects.count()
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: sms_webhook_smsmessage
"GET / HTTP/1.1" 500 136447
/Users/dennis/Projects/smsmobile/sms_webhook/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dennis/Projects/smsmobile/sms_webhook/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dennis/Projects/smsmobile/sms_webhook/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dennis/Projects/smsmobile/sms_webhook/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dennis/Projects/smsmobile/sms_webhook/mpesa_parser.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: sms_webhook_smsmessage

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/sms_webhook/views.py", line 155, in get
    total_sms = SMSMessage.objects.count()
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dennis/Projects/smsmobile/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: sms_webhook_smsmessage
"GET / HTTP/1.1" 500 136435
